controller:
  admin:
    username: "admin"
    password: "1561"
  serviceType: LoadBalancer
  servicePort: 8080
  installPlugins:
    - kubernetes:1.35.0
    - workflow-aggregator:2.6
    - credentials-binding:1.27
    - aws-credentials:1.29
    - amazon-ecr:1.4
    - docker-plugin:1.2.2
    - git:4.16.0

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

persistence:
  enabled: true
  storageClass: gp2
  size: 8Gi
