controller:
  serviceType: LoadBalancer
  servicePort: 8080
  admin:
    username: "admin"
    password: "1561"
  installPlugins:
    - kubernetes:4203.v1dd44f5b_1cf9   # keep if valid, otherwise use latest
    - workflow-aggregator:2.6          # stable release
    - git:5.2.1                        # valid release
    - docker-workflow:1.29             # stable release
    - amazon-ecr:1.7                   # valid release
  javaOpts: "-Djenkins.install.runSetupWizard=false"

persistence:
  enabled: true
  storageClass: "gp2"
  storageClassName: "gp2"
  accessMode: ReadWriteOnce
  size: 20Gi
