{{- if .Values.secrets.redis.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.redis.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: REDIS_HOST
      remoteRef:
        key: {{ .Values.secrets.redis.remoteRef }}
        property: host
    - secretKey: REDIS_PORT
      remoteRef:
        key: {{ .Values.secrets.redis.remoteRef }}
        property: port
{{- end }}
