{{- if .Values.secrets.rds.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.rds.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: {{ .Values.secrets.rds.remoteRef }}
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: {{ .Values.secrets.rds.remoteRef }}
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: {{ .Values.secrets.rds.remoteRef }}
        property: dbname
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.secrets.rds.remoteRef }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.rds.remoteRef }}
        property: password
{{- end }}
