serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::287043460305:role/aws-gitops-pipeline-dev-argocd-image-updater-role

config:
  registries:
    - name: ecr
      api_url: https://287043460305.dkr.ecr.us-east-1.amazonaws.com
      prefix: 287043460305.dkr.ecr.us-east-1.amazonaws.com
      credentials: ext:/scripts/ecr-login.sh
      default: true

authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      export HOME=/tmp
      echo "AWS:$(aws ecr get-login-password --region us-east-1)"
